import { useState, useEffect, useRef } from "react";
import { useQuery } from "convex/react";
import { api } from "../../convex/_generated/api";
import { Id } from "../../convex/_generated/dataModel";
import * as QRCode from "qrcode.react";
import { toast } from "sonner";
import { getAppBaseURL, getAllAccessibleURLs } from "../utils/network";

interface Table {
  _id: Id<"tables">;
  tableNumber: string;
  capacity: number;
  status: "available" | "occupied" | "reserved";
  currentOrderId?: Id<"orders">;
}

export function TableQRDisplay() {
  const tables = useQuery(api.tables.getAllTables);
  const [networkIPs, setNetworkIPs] = useState<string[]>([]);
  const [selectedIP, setSelectedIP] = useState("");
  const [isLoading, setIsLoading] = useState(true);
  const printRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    // Detect network interfaces using dynamic detection
    const detectNetworkInterfaces = async () => {
      setIsLoading(true);
      try {
        // Get all accessible URLs (works in both dev and prod)
        const urls = await getAllAccessibleURLs();

        // Debug log to see what URLs are detected
        console.log("Detected network URLs for tables:", urls);

        setNetworkIPs(urls);

        // Select the best URL as default (prefer non-localhost, private IPs)
        let defaultIP = urls[0]; // Start with the first URL

        // Try to find the first non-localhost URL that's a private IP
        const nonLocalhostPrivateURL = urls.find(
          (url) =>
            !url.includes("localhost") &&
            !url.includes("127.0.0.1") &&
            isPrivateURL(url)
        );

        if (nonLocalhostPrivateURL) {
          defaultIP = nonLocalhostPrivateURL;
        } else {
          // If no private IP found, try any non-localhost URL
          const nonLocalhostURL = urls.find(
            (url) => !url.includes("localhost") && !url.includes("127.0.0.1")
          );
          if (nonLocalhostURL) {
            defaultIP = nonLocalhostURL;
          }
        }

        console.log("Selected default IP:", defaultIP);
        setSelectedIP(defaultIP);
        setIsLoading(false);
      } catch (error) {
        console.warn("Could not detect network interfaces:", error);
        // Fallback to localhost
        const port = window.location.port || "5173";
        const defaultIPs = [`http://localhost:${port}`];

        setNetworkIPs(defaultIPs);
        setSelectedIP(defaultIPs[0]);
        setIsLoading(false);
      }
    };

    // Run the detection when component mounts
    void detectNetworkInterfaces();

    // Remove the interval that was causing constant loading
    // This was causing the loading state to appear constantly
  }, []);

  // Helper function to check if a URL contains a private IP
  function isPrivateURL(url: string): boolean {
    // Extract the hostname from the URL
    try {
      const urlObj = new URL(url);
      const hostname = urlObj.hostname;

      // Check if it's a private IP
      const parts = hostname.split(".").map(Number);

      // 10.x.x.x
      if (parts[0] === 10) return true;

      // 172.16.x.x - 172.31.x.x
      if (parts[0] === 172 && parts[1] >= 16 && parts[1] <= 31) return true;

      // 192.168.x.x
      if (parts[0] === 192 && parts[1] === 168) return true;

      return false;
    } catch (e) {
      return false;
    }
  }

  // Handle IP selection change
  const handleIPChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    setSelectedIP(e.target.value);
  };

  // Print all QR codes
  const printAllQRCodes = () => {
    // Create a new window for printing
    const printWindow = window.open("", "_blank");
    if (printWindow) {
      // Generate HTML with the same QR codes as displayed on the page
      const qrCodesHTML = tables?.map((table) => {
        const qrValue = `${selectedIP}/self-service/${table._id}`;
        return `
          <div class="qr-item">
            <div class="table-number">Table ${table.tableNumber}</div>
            <div class="qr-code-container">
              <div style="background: white; padding: 10px; border-radius: 8px; display: inline-block;">
                <!-- QR code will be generated by the browser's built-in QR rendering -->
                <div style="width: 150px; height: 150px; display: flex; align-items: center; justify-content: center; border: 1px solid #ddd;">
                  <div style="font-size: 10px; text-align: center; color: #666;">
                    Scan to order from Table ${table.tableNumber}
                    <br/>
                    <small>${qrValue}</small>
                  </div>
                </div>
              </div>
            </div>
            <div class="url">${qrValue}</div>
          </div>
        `;
      }).join("") || "";

      printWindow.document.write(`
        <!DOCTYPE html>
        <html>
          <head>
            <title>Table QR Codes</title>
            <meta charset="utf-8">
            <style>
              body { 
                font-family: Arial, sans-serif; 
                margin: 20px;
                padding: 0;
                background: white;
              }
              .header {
                text-align: center;
                margin-bottom: 30px;
                border-bottom: 2px solid #333;
                padding-bottom: 15px;
              }
              .header h1 {
                color: #333;
                margin: 0;
              }
              .header p {
                color: #666;
                margin: 5px 0 0 0;
              }
              .qr-grid {
                display: grid;
                grid-template-columns: repeat(3, 1fr);
                gap: 30px;
                margin-top: 20px;
              }
              .qr-item {
                text-align: center;
                padding: 15px;
                border: 1px solid #ddd;
                border-radius: 8px;
                box-shadow: 0 2px 4px rgba(0,0,0,0.1);
              }
              .qr-item .table-number {
                font-size: 18px;
                font-weight: bold;
                color: #e67e22;
              }
              .qr-code-container {
                margin: 15px 0;
                display: flex;
                justify-content: center;
              }
              .url {
                font-size: 12px;
                color: #666;
                word-break: break-all;
                background: #f8f8f8;
                padding: 8px;
                border-radius: 4px;
                margin-top: 10px;
              }
              .print-info {
                margin-top: 30px;
                text-align: center;
                font-size: 14px;
                color: #666;
                border-top: 1px solid #eee;
                padding-top: 15px;
              }
              @media print {
                body {
                  margin: 0;
                  padding: 20px;
                }
                .qr-grid {
                  grid-template-columns: repeat(3, 1fr);
                }
                .qr-item {
                  page-break-inside: avoid;
                }
              }
            </style>
          </head>
          <body>
            <div class="header">
              <h1>Table QR Codes</h1>
              <p>Scan to order from your table</p>
            </div>
            <div class="qr-grid">
              ${qrCodesHTML}
            </div>
            <div class="print-info">
              <p>Generated on ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}</p>
            </div>
            <script src="https://cdn.jsdelivr.net/npm/qrious@4.0.2/dist/qrious.min.js"></script>
            <script>
              // Generate QR codes using Qrious library
              document.addEventListener('DOMContentLoaded', function() {
                // Small delay to ensure library is loaded
                setTimeout(function() {
                  const qrContainers = document.querySelectorAll('.qr-code-container > div > div');
                  qrContainers.forEach(function(container) {
                    const url = container.querySelector('small').textContent;
                    if (url) {
                      try {
                        // Clear container
                        container.innerHTML = '';
                        
                        // Create canvas for QR code
                        const canvas = document.createElement('canvas');
                        container.appendChild(canvas);
                        
                        // Generate QR code
                        new QRious({
                          element: canvas,
                          value: url,
                          size: 150
                        });
                      } catch (e) {
                        console.error('QR Generation error:', e);
                        container.innerHTML = '<div style="color: red; font-size: 12px;">QR Failed</div>';
                      }
                    }
                  });
                  
                  // Print after a short delay to allow QR codes to render
                  setTimeout(function() {
                    window.print();
                  }, 1000);
                }, 500);
              });
            </script>
          </body>
        </html>
      `);
      printWindow.document.close();
    }
  };

  // Helper function to generate QR code as SVG string
  const generateQRCodeSVG = (value: string): string => {
    // Simple SVG-based QR code generator for printing
    // This creates a basic placeholder that should be visible when printed
    return `
      <svg width="130" height="130" viewBox="0 0 130 130" xmlns="http://www.w3.org/2000/svg">
        <rect width="130" height="130" fill="white"/>
        <rect x="10" y="10" width="20" height="20" fill="black"/>
        <rect x="40" y="10" width="20" height="20" fill="black"/>
        <rect x="70" y="10" width="20" height="20" fill="black"/>
        <rect x="100" y="10" width="20" height="20" fill="black"/>
        <rect x="10" y="40" width="20" height="20" fill="black"/>
        <rect x="70" y="40" width="20" height="20" fill="black"/>
        <rect x="100" y="40" width="20" height="20" fill="black"/>
        <rect x="10" y="70" width="20" height="20" fill="black"/>
        <rect x="40" y="70" width="20" height="20" fill="black"/>
        <rect x="70" y="70" width="20" height="20" fill="black"/>
        <rect x="100" y="70" width="20" height="20" fill="black"/>
        <rect x="10" y="100" width="20" height="20" fill="black"/>
        <rect x="40" y="100" width="20" height="20" fill="black"/>
        <rect x="70" y="100" width="20" height="20" fill="black"/>
        <rect x="100" y="100" width="20" height="20" fill="black"/>
        <text x="65" y="65" text-anchor="middle" dominant-baseline="middle" font-size="8" fill="black">QR:${value.substring(0, 15)}...</text>
      </svg>
    `;
  };

  return (
    <div className="bg-white rounded-xl p-6 shadow-sm border border-amber-100">
      <div className="flex justify-between items-center mb-4">
        <h3 className="text-lg font-semibold text-gray-900">Table QR Codes</h3>
        <button
          onClick={printAllQRCodes}
          className="px-4 py-2 bg-blue-600 text-white rounded-lg font-medium hover:bg-blue-700 transition-colors flex items-center gap-2"
        >
          <span>🖨️</span> Print All QR Codes
        </button>
      </div>

      <>
        <div className="mb-6">
          <label className="block text-sm font-medium text-gray-700 mb-2">
            Network Address for QR Codes
          </label>
          <div className="flex gap-2">
            <select
              value={selectedIP}
              onChange={handleIPChange}
              className="flex-1 px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-amber-500 focus:border-amber-500"
            >
              {networkIPs.map((url, index) => (
                <option key={index} value={url}>
                  {url}
                </option>
              ))}
            </select>
            <button
              onClick={() => {
                navigator.clipboard
                  .writeText(selectedIP)
                  .then(() => {
                    toast.success("Link copied to clipboard");
                  })
                  .catch(() => {
                    toast.error("Failed to copy link");
                  });
              }}
              className="px-4 py-2 bg-gray-200 text-gray-700 rounded-lg font-medium hover:bg-gray-300 transition-colors"
            >
              Copy
            </button>
          </div>
          <p className="mt-2 text-sm text-gray-500">
            Select the network address that devices on your local network can
            access
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {tables?.map((table) => (
            <div
              key={table._id}
              className="bg-gray-50 rounded-xl p-5 text-center border border-gray-200"
            >
              <h4 className="text-lg font-semibold text-gray-900 mb-3">
                Table {table.tableNumber}
              </h4>
              <div className="flex justify-center mb-3">
                <QRCode.QRCodeSVG
                  id={`qr-${table._id}`}
                  value={`${selectedIP}/self-service/${table._id}`}
                  size={150}
                  level={"H"}
                  includeMargin={true}
                  className="bg-white p-2 rounded-lg"
                />
              </div>
              <p className="text-sm text-gray-600 break-all">
                {selectedIP}/self-service/{table._id}
              </p>
              <div className="mt-3">
                <span
                  className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
                    table.status === "available"
                      ? "bg-green-100 text-green-800"
                      : table.status === "occupied"
                        ? "bg-yellow-100 text-yellow-800"
                        : "bg-red-100 text-red-800"
                  }`}
                >
                  {table.status.charAt(0).toUpperCase() + table.status.slice(1)}
                </span>
              </div>
            </div>
          ))}
        </div>
      </>
    </div>
  );
}

export default TableQRDisplay;
